#
# Copyright (c) 2016 Stefan Seefeld
# All rights reserved.
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)

sudo: required
dist: trusty

language: cpp


matrix:
  include:
    - compiler: x86_64-w64-mingw32-gcc
      env: CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ PYTHON=python3 CXXFLAGS=-std=c++11


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - scons
    - mingw-w64
    - clang
    - python-numpy
    - python-sphinx
    - python3-dev
    - python3-numpy
    - libboost-all-dev
    - xsltproc
    - docbook-xsl
    - python-docutils


cache:
  directories:
  - $HOME/Boost
  - $HOME/boost_python

before_install:
  # The Trusty image has several Python versions pre-installed compiled with
  # conflicting UCS2 and UCS4 unicode. Modify the PATH to skip the TravisCI python.
  # See https://github.com/travis-ci/travis-ci/issues/4948 for details.
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

install:
  - ls -la
  - pwd
  - echo HOME $HOME
  - |
     if [ ! -d $(pwd)/boost_python ]; then
       wget -O boost_python.tar.gz https://github.com/boostorg/python/archive/boost-1.66.0.tar.gz
       tar xf boost_python.tar.gz
       mv python-boost-1.66.0 boost_python
       echo created $(pwd)/boost_python
     fi
  - ls boost_python/
  # Install our own version of Boost (the subset we need) as the system version is
  # too old (for C++11 support).
  - rm -rf $HOME/Boost
  - |
     #set -e
     if [ ! -d $HOME/Boost ]; then
       echo "rebuilding Boost prerequisites"
       wget https://sourceforge.net/projects/boost/files/boost/1.66.0/boost_1_66_0.tar.gz/download
       tar xf download
       pushd boost_1_66_0
       export BOOST_JAM_TOOLSET_ROOT=/usr/x86_64-w64-mingw32
       ./bootstrap.sh -with-toolset=gcc -with-python-version=3.6
       if [ $? != 0 ]
       then
        cat bootstrap.log
        exit 1
       fi
       mkdir mingw
       export PATH=$(pwd)/mingw:$PATH
       ln -s /usr/bin/x86_64-w64-mingw32-gcc mingw/gcc
       ln -s /usr/bin/x86_64-w64-mingw32-g++ mingw/g++
       ls -la mingw/
       ./b2 toolset=gcc  link=shared libs/python/build/
       popd
     fi

script:
- cd boost_python
- ls stage/libs

after_failure:
- cat $HOME/build/TheCrazyT/boost_python_build_win/boost_1_66_0/bootstrap.log