sudo: required
dist: trusty
language: cpp
deploy:
  provider: bintray
  file: "$TRAVIS_BUILD_DIR/.bintray.js"
  user: thecrazyt
  skip_cleanup: true
  key:
    secure: Uz3N+q3yLMDMj7GdrWLKjwBX/admz/Vf4iywasl70dNAIaMO6xpMzKOCuT393DiMB2OvyFtRmJsTpIYttAguyZORrSt/SBzrNqN3jb3j71NOaW2oMD3XM5NdWLLXC+AWLFdOLRAePZhSBRD59EsMcQNWs7RwIdR3N5rhwjGm1c/bLjlP0P1CXQknw3AmXT5l27a/vKp1qGCJBhssrx7j+JOte0nATlw+DBGKLqlpTCtru547yzydgxy44VUbH90JNakmV9K6DKr0Uh71BgvxkDKhmsg1kIcAbeSenlVx2C7IpIioMGZVSije+lV4C+Au1sBm0BJ0gr4U3hz2utBQLFzrF5wp86H4o01KUAvbmCeDHw0vUAxxoDHfWj85Ia2cL0L4tGFSt+bp7/88FH+DTntwb8VwyUqwkXKQODL7hfpWiUzVkZc2vavO6J0INENNzNJweSkHCJbfjmsJI/SMK4U9STAhbSJ+xTn7lNz3z+B17cZWgPYRBaFmlMoo3OYhZJiqMa+2ZZlZOZWJY8p/os9BfT9f6KG5HJdUZWM61H2/Qoo/pcHmGwlSqV22fCDtjw2n9Mkwg2XjOayJJMQEefT4zzxK3jgm6vE5AgP1t1x2Vw328t+DdmWcyPyHQnj9b2x6zy5CK3FrO5rVOh4g29XlZaJnU9a712oIPmNx92k=
  on:
    all_branches: true
services:
    - docker
#cache:
#  directories:
#  - "$HOME/Boost"
before_install:
- chmod +x .travis_*
- docker pull ubuntu:bionic
- docker images
- docker run -t --rm -v $(pwd):/travis_build ubuntu:bionic /bin/bash -c "cd /travis_build/ && ./.travis_build"
- ls /home/travis/build/TheCrazyT/boost_python_build_win/build/

script:
- echo 'skipping configure && make && make test'