sudo: required
dist: trusty
language: cpp
deploy:
  provider: bintray
  file: "$TRAVIS_BUILD_DIR/.bintray.js"
  user: thecrazyt
  skip_cleanup: true
  key:
    secure: Uz3N+q3yLMDMj7GdrWLKjwBX/admz/Vf4iywasl70dNAIaMO6xpMzKOCuT393DiMB2OvyFtRmJsTpIYttAguyZORrSt/SBzrNqN3jb3j71NOaW2oMD3XM5NdWLLXC+AWLFdOLRAePZhSBRD59EsMcQNWs7RwIdR3N5rhwjGm1c/bLjlP0P1CXQknw3AmXT5l27a/vKp1qGCJBhssrx7j+JOte0nATlw+DBGKLqlpTCtru547yzydgxy44VUbH90JNakmV9K6DKr0Uh71BgvxkDKhmsg1kIcAbeSenlVx2C7IpIioMGZVSije+lV4C+Au1sBm0BJ0gr4U3hz2utBQLFzrF5wp86H4o01KUAvbmCeDHw0vUAxxoDHfWj85Ia2cL0L4tGFSt+bp7/88FH+DTntwb8VwyUqwkXKQODL7hfpWiUzVkZc2vavO6J0INENNzNJweSkHCJbfjmsJI/SMK4U9STAhbSJ+xTn7lNz3z+B17cZWgPYRBaFmlMoo3OYhZJiqMa+2ZZlZOZWJY8p/os9BfT9f6KG5HJdUZWM61H2/Qoo/pcHmGwlSqV22fCDtjw2n9Mkwg2XjOayJJMQEefT4zzxK3jgm6vE5AgP1t1x2Vw328t+DdmWcyPyHQnj9b2x6zy5CK3FrO5rVOh4g29XlZaJnU9a712oIPmNx92k=
  on:
    all_branches: true
matrix:
  include:
  - compiler: x86_64-w64-mingw32-gcc
    env: CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ PYTHON=python3 CXXFLAGS=-std=c++11
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - p7zip
    - scons
    - clang
    - python-numpy
    - python-sphinx
    - python3
    - python3-dev
    - python3-numpy
    - libboost-all-dev
    - xsltproc
    - docbook-xsl
    - python-docutils
#cache:
#  directories:
#  - "$HOME/Boost"
before_install:
- apt-get -qq update
- apt-get install -y gcc-mingw-w64-x86-64
- apt-get install -y g++-mingw-w64-x86-64
- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |
  sed "s|::|:|g")
- sudo sed 's/\(.include *.ansidecl.h.\)/\/\/\1/g' -i /usr/share/mingw-w64/include/ieeefp.h
script:
- ls -la
- pwd
- echo HOME $HOME
- wget http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-python3-3.6.5-1-any.pkg.tar.xz
- wget https://github.com/TheCrazyT/roboschool/releases/download/v0.0.1-beta.1/precompiled_headers.7z
- 7zr x precompiled_headers.7z 1>/dev/null 2>/dev/null
- tar xf mingw-w64-x86_64-python3-3.6.5-1-any.pkg.tar.xz
- rm -rf $HOME/Boost
- |
  #set -e
  if [ ! -d $HOME/Boost ]; then
    echo "rebuilding Boost prerequisites"
    wget https://sourceforge.net/projects/boost/files/boost/1.66.0/boost_1_66_0.tar.gz/download
    tar xf download
    pushd boost_1_66_0
    export BOOST_JAM_TOOLSET_ROOT=/usr/x86_64-w64-mingw32
    ./bootstrap.sh -with-toolset=gcc -with-python-version=3.6
    if [ $? != 0 ]
    then
     cat bootstrap.log
     exit 1
    fi
    mkdir mingw
    #export PATH=$(pwd)/mingw:$PATH
    #ln -s /usr/bin/x86_64-w64-mingw32-gcc mingw/gcc
    #ln -s /usr/bin/x86_64-w64-mingw32-g++ mingw/g++
    echo 'using gcc : 7.2 : x86_64-w64-mingw32-g++ ;' > ~/user-config.jam
    #ls -la ../mingw64/include/python3.6m
    #echo 'using python : 3.6m : /usr/bin/python3.6 : '$(pwd)'/../mingw64/include/python3.6m : '$(pwd)'/../mingw64/lib : <target-os>windows ;' >> ~/user-config.jam
    echo 'using python : 3.6 : /bin/false : '$(pwd)'/../mingw64/include/python3.6m : '$(pwd)'/../precompiled/ : <target-os>windows ;' >> ~/user-config.jam
    #echo 'using python : 3.6m : /usr/bin/python3 : '$(pwd)'/../mingw64/include/python3.6m : '$(pwd)'/../mingw64/lib : <target-os>windows ;' >> ~/user-config.jam
    #user-config.jam in home directory
    #python.jam remove "lib dl" and "lib util"
    #--user-config user-config.jam
    #./b2 toolset=gcc  link=shared target-os=windows address-model=64 architecture=x86 --with-python veriant=release cxxflags='cxxflags='-I"'$(pwd)'/../mingw64/include/python3.6m/" -DHAVE_SSIZE_T -DPY_FORMAT_SIZE_T="l" -DPY_FORMAT_LONG_LONG="ll"'
    #ToDo: eliminate libgcc_s_sjlj-1.dll dependency
    x86_64-w64-mingw32-g++ --version
    ./b2 -d2 toolset=gcc  link=shared target-os=windows address-model=64 architecture=x86 --debug-configuration --with-python variant=release  cflags='-static-libgcc -static-libstdc++' cxxflags='-static-libgcc -static-libstdc++' linkflags='-static-libgcc -static-libstdc++'
    popd
  fi
- pushd boost_1_66_0
- pwd
- ls stage/lib
- mkdir ../build/
#- python -c "import sys;content=open('stage/lib/libboost_python3.dll','rb').read();content=content.replace(b'libpython3.6.dll',bytes('Python36.dll\0\0\0\0'));open('stage/lib/libboost_python3-mgw72-mt-x64-1_66.dll','wb').write(content)"
- cp stage/lib/* ../build/
- popd
- ls /home/travis/build/TheCrazyT/boost_python_build_win/build/
after_failure:
- cat $HOME/build/TheCrazyT/boost_python_build_win/boost_1_66_0/bootstrap.log
